"""UI-only report viewer helpers.

This module owns report viewer dialogs and rendering. It intentionally keeps
all data fetching outside (for example in report_generator / reports_repo).
"""

from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QDialog, QHBoxLayout, QLabel, QLineEdit, QPlainTextEdit, QVBoxLayout, QWidget

# Viewer size policy by report type.
REPORT_VIEWER_SIZES = {
    'detail': (900, 620),
    'summary': (760, 520),
    'chart': (980, 680),
    'inactivity': (720, 500),
}
DEFAULT_REPORT_VIEWER_SIZE = (760, 520)


def _create_overlay(parent_dlg: QDialog):
    """Create a dim background overlay above the report menu dialog."""
    try:
        overlay = QWidget(parent_dlg)
        overlay.setObjectName('reportViewerOverlay')
        overlay.setGeometry(parent_dlg.rect())
        overlay.show()
        overlay.raise_()
        return overlay
    except Exception:
        return None


def _cleanup_overlay(overlay):
    """Dispose the dim background overlay if it exists."""
    try:
        if overlay is not None:
            overlay.hide()
            overlay.deleteLater()
    except Exception:
        pass


def _build_shell(parent_dlg: QDialog, *, report_type: str):
    """Create the modal viewer shell with titlebar close button."""
    rpt = str(report_type or 'summary').strip().lower()
    size = REPORT_VIEWER_SIZES.get(rpt, DEFAULT_REPORT_VIEWER_SIZE)

    viewer = QDialog(parent_dlg)
    viewer.setObjectName('reportViewerDialog')
    viewer.setModal(True)
    viewer.setWindowModality(Qt.WindowModal)
    viewer.setWindowFlags(viewer.windowFlags() | Qt.WindowTitleHint | Qt.WindowCloseButtonHint)
    viewer.setWindowTitle(f"{rpt.capitalize()} Report Viewer")
    viewer.resize(int(size[0]), int(size[1]))

    layout = QVBoxLayout(viewer)
    layout.setContentsMargins(16, 16, 16, 16)
    layout.setSpacing(10)

    return viewer, layout


def _format_detailed_report_text(report: dict) -> str:
    """Render fixed-width text for detailed report data."""
    if not isinstance(report, dict):
        report = {}

    sales = report.get('sales_summary') or {}
    payments = report.get('payment_breakdown') or []
    categories = report.get('categories') or []
    top_products = report.get('top_products') or []
    outflows = report.get('cash_outflows') or []
    excluded = report.get('excluded') or {}
    header = report.get('header') or {}

    lines = [
        'DETAILED SALES REPORT',
        '=' * 72,
        f"Period        : {header.get('period_from') or '-'} to {header.get('period_to') or '-'}",
        f"Generated At  : {header.get('generated_at') or '-'}",
        f"Generated By  : {header.get('generated_by') or '-'}",
        '',
        '1. SALES SUMMARY',
        '-' * 72,
        f"PAID Receipt Count : {int(sales.get('paid_receipt_count') or 0)}",
        f"Gross Sales        : {float(sales.get('gross_sales') or 0.0):.2f}",
        f"Refund Outflow     : {float(sales.get('less_refund_outflow') or 0.0):.2f}",
        f"Vendor Outflow     : {float(sales.get('less_vendor_outflow') or 0.0):.2f}",
        f"Net After Outflow  : {float(sales.get('net_after_outflows') or 0.0):.2f}",
        '',
        '2. PAYMENT METHOD BREAKDOWN',
        '-' * 72,
    ]

    if payments:
        for row in payments:
            lines.append(f"{str(row.get('method') or ''):20} : {float(row.get('amount') or 0.0):.2f}")
    else:
        lines.append('No payment rows.')

    lines.extend(['', '3. CATEGORY BREAKDOWN WITH PRODUCTS', '-' * 72])
    if categories:
        for cat in categories:
            cat_name = str(cat.get('category_name') or 'Uncategorized')
            cat_total = float(cat.get('category_total') or 0.0)
            lines.append(f"Category: {cat_name} | Total: {cat_total:.2f}")
            for prod in (cat.get('products') or []):
                lines.append(
                    f"  - {str(prod.get('product_name') or ''):24} "
                    f"{float(prod.get('qty_sold') or 0.0):.3g} {str(prod.get('unit') or ''):6} "
                    f"{float(prod.get('line_sales') or 0.0):.2f}"
                )
    else:
        lines.append('No category/product rows.')

    lines.extend(['', '4. TOP 10 PRODUCTS', '-' * 72])
    if top_products:
        for row in top_products:
            lines.append(
                f"{int(row.get('rank') or 0):>2}. {str(row.get('product_name') or ''):25} "
                f"{float(row.get('qty_sold') or 0.0):.3g} {str(row.get('unit') or ''):6} "
                f"{float(row.get('line_sales') or 0.0):.2f}"
            )
    else:
        lines.append('No product rows.')

    lines.extend(['', '5. CASH OUTFLOWS DETAIL', '-' * 72])
    if outflows:
        for row in outflows:
            lines.append(
                f"{str(row.get('outflow_type') or ''):12} "
                f"{str(row.get('created_at') or ''):20} "
                f"{str(row.get('cashier') or ''):10} "
                f"{float(row.get('amount') or 0.0):.2f} "
                f"{str(row.get('note') or '')}"
            )
    else:
        lines.append('No outflow rows.')

    lines.extend(
        [
            '',
            '6. EXCLUDED / OPERATIONAL SECTION',
            '-' * 72,
            f"UNPAID Receipts Count    : {int(excluded.get('unpaid_receipts_count') or 0)}",
            f"UNPAID Receipts Total    : {float(excluded.get('unpaid_receipts_total') or 0.0):.2f}",
            f"CANCELLED Receipts Count : {int(excluded.get('cancelled_receipts_count') or 0)}",
            f"CANCELLED Receipts Total : {float(excluded.get('cancelled_receipts_total') or 0.0):.2f}",
            '',
            'END OF REPORT',
        ]
    )
    return '\n'.join(lines)


def _render_placeholder(layout: QVBoxLayout, *, report_type: str) -> None:
    """Render placeholder content for non-detailed report types."""
    rpt = str(report_type or 'summary').strip().lower()
    msg = QLabel(f'No {rpt} content available.')
    msg.setObjectName('reportViewerMessageLabel')
    msg.setAlignment(Qt.AlignCenter)
    msg.setWordWrap(True)
    layout.addWidget(msg)


def _render_detailed(layout: QVBoxLayout, *, report_data: dict) -> None:
    """Render detailed text report with search and scrollbars."""
    search_row = QHBoxLayout()
    search_row.setSpacing(8)

    search_label = QLabel('Find:')
    search_label.setObjectName('reportViewerSearchLabel')
    search_row.addWidget(search_label)

    search_input = QLineEdit()
    search_input.setObjectName('reportViewerSearchInput')
    search_input.setPlaceholderText('Search text in report...')
    search_row.addWidget(search_input)

    search_row.addStretch()
    layout.addLayout(search_row)

    text_box = QPlainTextEdit()
    text_box.setObjectName('reportViewerTextEdit')
    text_box.setReadOnly(True)
    text_box.setLineWrapMode(QPlainTextEdit.NoWrap)
    text_box.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
    text_box.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
    text_box.setPlainText(_format_detailed_report_text(report_data))
    layout.addWidget(text_box)

    def _find_text() -> None:
        term = search_input.text()
        if not term:
            return
        if not text_box.find(term):
            cursor = text_box.textCursor()
            cursor.movePosition(cursor.Start)
            text_box.setTextCursor(cursor)
            text_box.find(term)

    search_input.returnPressed.connect(_find_text)


def open_report_viewer(parent_dlg: QDialog, *, report_type: str, report_data: dict = None) -> None:
    """Open report viewer with a shared shell and type-specific renderer."""
    overlay = _create_overlay(parent_dlg)
    try:
        rpt = str(report_type or 'summary').strip().lower()
        viewer, layout = _build_shell(parent_dlg, report_type=rpt)

        if rpt == 'detail':
            _render_detailed(layout, report_data=report_data or {})
        else:
            _render_placeholder(layout, report_type=rpt)

        viewer.exec_()
    finally:
        _cleanup_overlay(overlay)
